// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/camera-layouts/CameraFirstHero.tsx": () => import("../components/mockups/camera-layouts/CameraFirstHero.tsx")
};
